services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./apps/frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_URL=http://localhost:3000
      # - NEXT_PUBLIC_URL=https://myclipboard.online
      - NODE_ENV=development
    command: sh -c "npm i -g pnpm && pnpm install && pnpm run dev"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./apps/backend:/app
      - ./uploads:/app/uploads # Mount uploads directory for file storage
    ports:
      - "3001:3001" # This port must be exported and accessed by the frontend for the socket connection
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    command: sh -c "npm i -g pnpm && pnpm install && pnpm run dev"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - storage-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - storage-network

networks:
  storage-network:
    driver: bridge

volumes:
  redis_data:
